export ZSH="$HOME/.oh-my-zsh"
export VIRTUAL_ENV_DISABLE_PROMPT=1

ZSH_THEME="agnoster"
DEFAULT_USER="$USER"

plugins=(
  git
  macos
  ssh-agent
  zsh-syntax-highlighting
  zsh-history-substring-search
)

source $ZSH/oh-my-zsh.sh

# Load lingti configs
for config_file ($HOME/.lingti/zsh/*.zsh) source $config_file

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# bun completions
[ -s "~/.bun/_bun" ] && source "~/.bun/_bun"
# OpenClaw Completion
source "/Users/alex/.openclaw/completions/openclaw.zsh"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
